### ISSUE TITLE
multi-line comment warning

### ISSUE THREAD

**Issue by Bomel** [gipert/progressbar#3]
While compiling, I get a multi-line comment warning.

https://github.com/gipert/progressbar/blob/9fcfec70942227e733eea487b3ba79e13f59e207/progressbar.hpp#L26

I mean, it is not that big of a deal, but it's just not nice to get warnings while compiling. You can add a `.` in line 26 for example.

**Comment by gipert** [comment]
Thanks for reminding me about this. Fixed in 1425e0a.
